
os:
  - linux

language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE="on"

gobuild_args: -v

script: bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build